### ISSUE TITLE
Please remove the nicknames from the backlog/corpus

### ISSUE THREAD

**Issue by astrofra** [phaazon/kwak#4]
Please remove the nicknames from the backlog/corpus, so that Kwak doesn't quote or mentions nicknames.
Implementation could be based on a fixed blacklist of names, possibly dynamically updated with the live list of nicknames found in the current channel Kwak is logged into.

**Comment by flure** [comment]
Or replace them with a phonetic equivalent but that will not trigger a highlight

**Comment by phaazon** [comment]
You mean a hilight!

**Comment by phaazon** [comment]
I’m not sure I can fix that in an easy way. I might introduce a blacklist but I’m not sure it’ll be correctly used.
